[firebird]
host=localhost
port=3050
user=SYSDBA
password=masterkey

; folder gdje se nalazi .FDB datoteka
dir_fdb=C:\eRacunImport\

; naziv .FDB datoteke
fdb_file=LEONARDO-2026IS.FDB

; charset konekcije na bazu (odgovara WIN1250/PXW_SLOV kolonama u shemi)
charset=WIN1250

; folder gdje se nalaze .XML datoteke s eRačunima
dir_xml=C:\eRacunXML\

; iznos povratne naknade
povratna_naknada=0.1

;korisnik nije u sustavu PDV-a
nije_obveznik_PDV=F

[primka]
; ID korisnika (FB.KORISNICI.IDKOR) koji se upisuje kao SISUSER kod knjiženja primke
idsisuser=9

; idtransakcijski - koristit će se kod knjiženja primke (GASZG/GASST)
idtransakcijski=2
